### ISSUE TITLE
Won't work from Windows 10/11 Multi-Session Azure VMs

### ISSUE THREAD

**Issue by Shadimar** [ScottKnights/FSLogix#1]
Is it possible to tweak this to work when migrating profiles from Windows 10/11 Multi-session VMs in Azure?   I get a powershell error that states it cannot be run from a client OS, only server OS.  :(

**Comment by ScottKnights** [comment]
I can have a look, but it isn't likely to be anytime soon I am afraid due to other workload commitments. May be related to the get-windowsfeature and install-windowsfeature CMDLets which are for managing features on Windows servers. 

Try installing the Windows client RSAT **Active Directory Domain Services and Lightweight Directory Services Tools** and comment out or remove the section of the script that checks for and installs the server RSAT feature (lines 436-459)
https://www.microsoft.com/en-au/download/details.aspx?id=45520

IF it still doesn't work, can you provide more information? Does the error message give any line numbers or other detail?

**Comment by Shadimar** [comment]
I will try these things and let you know!  I'll include any errors I get and I appreciate your time!

**Comment by Shadimar** [comment]
So, I was able to get the script to run by commenting out the RSAT lines you suggested.  I then got the profile selection screen and when I chose a profile it looks like it migrated the profile but it did throw a few errors.  I'm hopeful that it actually worked but can't confirm until tomorrow.  Thanks for the suggestion!  Here are the errors I got..
![Errors jpg](https://user-images.githubusercontent.com/54362489/150895853-f258d1c5-5aa6-4664-9a80-fd1f1c0e6f55.png)

**Comment by ScottKnights** [comment]
Those two lines are attempting to set permissions on the folder and container. The error indicates you don't have permission to do this. Should really add some more error trapping there, but the assumption is you would be running as administrator so this wouldn't be a problem. Based on this, it looks like the profile conversion has worked, but you will probably need to check the permissions to make sure the user has the required access. I haven't used Multi session Windows in Azure, so am not sure what the issue is.

**Comment by Shadimar** [comment]
It did work!  Thanks for your help!
