### ISSUE TITLE
Problem Setting Owner

### ISSUE THREAD

**Issue by iPodHacks142** [ScottKnights/FSLogix#2]
I'm trying to use your local to FSLogix profile migration script but am having a problem with the part that sets the owner of the folder and VHD. Whenever it attempts that part I get this error:

set-acl : The security identifier is not allowed to be the owner of this object.
At I:\Scripts\FSLogix-LocalProfileToProfileContainer1.ps1:108 char:2
set-acl -path $fldname -aclobject $fldacl

CategoryInfo          : InvalidOperation: (A:\Profiles\S-1...-1125_ben.lee:String) [Set-Acl], InvalidOperation Exception
FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.SetAclCommand

I also get an error that the 'wsearch' service cannot be found. 

This is running on Windows Server 2012 R2. I have tried with both the AD user list and the text file.

**Comment by ScottKnights** [comment]
I have only used this with PowerShell 5 and had not tested it with PowerShell 4. I have just tested set-acl on a 2012R2 machine with PowerShell 4 and can reproduce the error you are seeing. Unfortunately, I will be away for a month and will not have time to look at an alternative until the end of July. Are you using PowerShell 4? If yes, can you upgrade to PowerShell 5 and try again?

Not sure why you are getting an error for wsearch, since errors should be suppressed if the service doesn't exist or isn't running. Just comment out the service restart line.

**Comment by iPodHacks142** [comment]
I managed to get around it by replacing the set-acl commands with icacls.
